name: admin_seller
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.6
  dio: ^5.1.2
  socket_io_client: ^2.0.2
  firebase_messaging: ^14.6.2
  firebase_core: ^2.13.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  dropdown_button2: ^2.1.3
  hive: ^2.2.3
  hive_generator: ^2.0.0
  path_provider: ^2.0.15
  flutter_local_notifications: ^14.1.1
  shimmer: ^3.0.0
  flutter_typeahead: ^4.6.1
  rename: ^2.1.1
  mask_text_input_formatter: ^2.4.0
  connectivity_plus: ^4.0.1
  internet_connection_checker: ^1.0.0+1
  fluttertoast: ^8.2.2
  intl: ^0.18.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf      
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf        
    - family: ManropeLight
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf      
    - family: ManropeSemibold
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf        
    - family: ManropeMedium
      fonts:
        - asset: assets/fonts/Manrope-Medium.ttf
        
